# Mongo Config
spring:
  data: 
    mongodb:
      # host: mongodb-server
      uri: mongodb://dev-cqrs-db-account:c1isb8FSDvQAVpCuEOJr9wcstDadcpYFnGuqA74StiZecseJHFExNvCedbRNMb537B5MsA2yQ5aYACDbgp8nwQ==@dev-cqrs-db-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dev-cqrs-db-account@
      database: dev-cqrs-mongodb
      # port: 27017

# kafka:
#   partitions: 1
#   replicas: 1

topic-key: qFxSyPhWHWhz8KYJmQNJ8d6eENgvN8Crcho7HnSruCo=
topic-endpoint: https://dev-cqrs-eventgrid-topic.westeurope-1.eventgrid.azure.net/api/events
