# Mongo Config
spring:
  data: 
    mongodb:
      # host: mongodb-server
      uri: mongodb://dev-cqrs-db-account:PxOUQORfSV5XulOB2SkePRzeEJCpPsMCz0eD2W19PPvB96kChX58KvKufZnP336lB68mzMvhRva7ACDbA9SZ3A==@dev-cqrs-db-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dev-cqrs-db-account@
      database: dev-cqrs-mongodb
      # port: 27017

# kafka:
#   partitions: 1
#   replicas: 1

