# Mongo Config
spring:
  data: 
    mongodb:
      # host: mongodb-server
      uri: mongodb://dev-cqrs-db-account:pUMiy1LsHFQrPcGgzEFuDXDtNf79cQCNpC180mPJIaCT809670pS1lbcpP0m0VDZYvLxvZCbYR5kACDbAXc7dQ==@dev-cqrs-db-account.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@dev-cqrs-db-account@
      database: dev-cqrs-mongodb
      # port: 27017

# kafka:
#   partitions: 1
#   replicas: 1

topic-key: XpblHLk+2uT3qzpyIIbw+qDHwnBhjEZVHyiWjYxL8GY=
topic-endpoint: https://dev-cqrs-eventgrid-topic.westeurope-1.eventgrid.azure.net/api/events
